# -*- coding: utf-8 -*-
#
# This file is part of Invenio-PIDStore
# Copyright (C) 2015 CERN
#
# Invenio is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# Invenio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Invenio; if not, write to the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

notifications:
  email: false

services:
  - mysql
  - redis

language: python

cache:
  - apt
  - pip

env:
  - REQUIREMENTS=lowest REXTRAS=docs,test
  - REQUIREMENTS=release REXTRAS=docs,test
  - REQUIREMENTS=devel REXTRAS=docs,test

python:
  - "2.7"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install python-dev"
  - "travis_retry pip install --upgrade pip"
  - "travis_retry pip install mock"
  - "python requirements.py --extras=$REXTRAS --level=min > .travis-lowest-requirements.txt"
  - "python requirements.py --extras=$REXTRAS --level=pypi > .travis-release-requirements.txt"
  - "python requirements.py --extras=$REXTRAS --level=dev > .travis-devel-requirements.txt"

install:
  - "travis_retry pip install unittest2"
  - "travis_retry pip install -r .travis-$REQUIREMENTS-requirements.txt --allow-all-external --quiet"
  - "travis_retry pip install -e .[$REXTRAS] --quiet --process-dependency-links"

before_script:
  - "inveniomanage database init --yes-i-know || echo ':('"
  - "inveniomanage database create --quiet || echo ':('"

script:
  - "sphinx-build -qnN docs docs/_build/html"
  - "python setup.py test"

after_success:
  - coveralls
